tap 'homebrew/bundle'
tap 'homebrew/php'

brew 'ack'
brew 'autoconf'
brew 'autojump'
brew 'automake'
brew 'checkbashisms'
brew 'cmake'
brew 'coreutils'
brew 'cowsay'
brew 'direnv'
brew 'ffmpeg'
brew 'figlet'
brew 'fzf'
brew 'gawk'
brew 'gdbm'
brew 'gifsicle'
brew 'git'
brew 'go', args: ['cross-compile-common']
brew 'jq'
brew 'lame'
brew 'libevent'
brew 'nkf'
brew 'node.js'
brew 'nodebrew'
brew 'mhash'
brew 'mysql'
brew 'openssl'
brew 'peco'
brew 'phantomjs'
brew 'homebrew/php/phpmyadmin'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'shellcheck'
brew 'sqlite'
brew 'terminal-notifier'
brew 'tig', args: ['with-docs']
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'wget'
brew 'yarn'
brew 'zplug'
brew 'zsh', args: ['disable-etcdir']
brew 'zsh-completions'
